[package]
name = "git-status-prompt"
version = "0.1.0"
authors = ["Adrien Samson <adrien@adriensamson.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.1"